id = "cave_entrance"
name = "Cave Entrance"
description = "A gaping maw in the earth, breathing cool, damp air."
terminal = true
grid = """
##############
#,...~.......#
#........~...#
#...~........#
#........~...#
#..~.........#
##############
"""

[[triggers]]
position = [1, 1]
type = "travel"
auto_trigger = true
target_id = "overgrown_path"
once = false

[[triggers]]
position = [10, 4]
type = "encounter"
target_id = "orc_warrior"
once = false
